name: CI/CD Pipeline for Hugging Face Spaces

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Hugging Face Docker Registry
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "${HF_TOKEN}" | docker login registry.huggingface.co -u ${{ secrets.HF_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=registry.huggingface.co/${{ secrets.HF_USERNAME }}/dynamic-pricing:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy-to-huggingface-space:
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Log in to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token "${HF_TOKEN}"

      - name: Create Hugging Face Space (if not exists)
        run: |
          huggingface-cli repo create dynamic-pricing --type space --space-sdk docker --yes || true

      - name: Push Docker Image Reference to Hugging Face Space
        run: |
          echo "registry.huggingface.co/${{ secrets.HF_USERNAME }}/dynamic-pricing:latest" > docker_image.txt
          huggingface-cli upload --repo-type space --repo-id ${{ secrets.HF_USERNAME }}/dynamic-pricing --path docker_image.txt --commit-message "Update Docker image reference"
