name: CI/CD Pipeline for Hugging Face Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Hugging Face Docker Registry
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "${HF_TOKEN}" | docker login registry.huggingface.co -u ${{ secrets.HF_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=registry.huggingface.co/${{ secrets.HF_USERNAME }}/dynamic-pricing:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
