name: CI/CD Pipeline for Hugging Face Spaces

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Hugging Face Docker Registry
      - name: Log in to Hugging Face Docker Registry
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin registry.huggingface.co

      # Step 4: Build and Push Docker Image to Hugging Face Docker Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.huggingface.co/${{ secrets.HF_USERNAME }}/dynamic-pricing:latest .
          docker push registry.huggingface.co/${{ secrets.HF_USERNAME }}/dynamic-pricing:latest

  deploy-to-huggingface-space:
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # Ensure this job runs after the Docker image is pushed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install huggingface_hub CLI
      - name: Install huggingface_hub
        run: pip install huggingface_hub

      # Step 3: Log in to Hugging Face
      - name: Log in to Hugging Face
        run: huggingface-cli login --token "${{ secrets.HF_TOKEN }}"

      # Step 4: Create or Update Hugging Face Space
      - name: Create or Update Hugging Face Space
        run: |
          huggingface-cli repo create dynamic-pricing --organization ${{ secrets.HF_USERNAME }} --type space --space-sdk docker --yes || true

      # Step 5: Update Space with Docker Image
      - name: Update Space with Docker Image
        run: |
          huggingface-cli update-space --repo ${{ secrets.HF_USERNAME }}/dynamic-pricing --docker-image registry.huggingface.co/${{ secrets.HF_USERNAME }}/dynamic-pricing:latest